version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_blog
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lfu"]
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/ai_blog
      REDIS_URL: redis://redis:6379/0
      OLLAMA_BASE_URL: http://ollama:11434
    depends_on:
      - db
      - redis
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - ./server/storage:/app/server/storage

  client:
    image: node:20
    working_dir: /app
    command: bash -lc "npm i && HOST=0.0.0.0 npm run dev"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
      SERVER_API_BASE_URL: http://server:8000
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
    depends_on:
      - server

volumes:
  db_data:
  ollama_data:
